config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#home'

  get '/login/' , to: 'users#login', as: 'login'
  delete '/logout', to: 'users#logout', as: 'logout'
  get '/find_user/' , to: 'users#find_user', as: 'find_user'
  post 'books/:id', to: 'books#favorite', as: 'favorite'
  post 'rhymes/:id', to: 'rhymes#favorite'
  

  resources :users
  resources :books, only: [:show, :index]
  resources :rhymes, only: [:show, :index] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :book_category
  has_many :favorite_books
  has_many :users, through: :favorite_books
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
  has_many :books
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/favorite_rhyme.rb
class FavoriteRhyme < ApplicationRecord
  belongs_to :rhyme
  belongs_to :user
end

app/models/rhyme.rb
class Rhyme < ApplicationRecord
  belongs_to :rhyme_category
  has_many :favorite_rhymes
  has_many :users, through: :favorite_rhymes
end

app/models/rhyme_category.rb
class RhymeCategory < ApplicationRecord
  has_many :rhymes
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorite_books
  has_many :books, through: :favorite_books
  has_many :favorite_rhymes
  has_many :rhymes, through: :favorite_rhymes
  validates :username, uniqueness: true, presence: true
  validates :name, presence: true
  validates :age, presence: true
  before_validation :make_caps

  private

  def make_caps
    self.name.capitalize!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :auth

  def auth
    if session[:user_id]
      # goes to action
    else
      redirect_to '/'
    end
  end

  def display_nav? 
    controller_actions = [ 'users#new', 'users#login', 'users#home' ]
    current_controller_action = [params[:controller], params[:action]].join("#") 
    return controller_actions.include?(current_controller_action) ? false : true
  end

  helper_method :display_nav?
end

app/controllers/book_categories_controller.rb
class BookCategoriesController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @categories = BookCategory.all
    end

    def show
        @user = User.find(session[:user_id])
        @book = Book.find(params[:id])
    end

    def favorite 
        @user = User.find(session[:user_id])
        @book = Book.find(params[:id])
        if find_favorite_book
            find_favorite_book.delete
        else
            FavoriteBook.create(user_id: session[:user_id], book_id: @book.id)
        end
        redirect_to book_path(@book)
    end

    private

    def find_favorite_book
        FavoriteBook.find_by(user_id: @user.id, book_id: @book.id)
    end
end

app/controllers/favorite_books_controller.rb
class FavoriteBooksController < ApplicationController
end

app/controllers/favorite_rhymes_controller.rb
class FavoriteRhymesController < ApplicationController

end

app/controllers/rhymes_controller.rb
class RhymesController < ApplicationController

    def index
        @categories = RhymeCategory.all
    end

    def show
        @user = User.find(session[:user_id])
        @rhyme = Rhyme.find(params[:id])
    end

    def favorite
        @user = User.find(session[:user_id])
        @rhyme = Rhyme.find(params[:id])
        if find_favorite_rhyme
            find_favorite_rhyme.delete
        else
            FavoriteRhyme.create(user_id: session[:user_id], rhyme_id: @rhyme.id)
        end
        redirect_to rhyme_path(@rhyme)
    end
    
    private

    def find_favorite_rhyme
        FavoriteRhyme.find_by(user_id: @user.id, rhyme_id: @rhyme.id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :auth, only: [:new, :create, :login, :find_user, :home]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path
    end
  end

  def show
    @user = User.find(params[:id])
   
    if @user.id == session[:user_id]
      # render show
    else
      flash[:errors] =  "You tried to view another user's page, here is your page."
      redirect_to user_path(session[:user_id])
    end
  end

  def destroy
    @user = User.find(params[:id])
    FavoriteBook.delete_by(user_id: @user.id)
    FavoriteRhyme.delete_by(user_id: @user.id)
    @user.delete
    redirect_to :root
  end

  def login
  end

  def find_user
    @user = User.find_by(username: params[:username] )
    
    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:failed] = "Please enter a valid username. #{params[:username]} doesn't exist."
      redirect_to login_path
    end
  end

  def logout
    session.delete :user_id
    redirect_to '/'
  end

  def home
  end

  private 

  def user_params 
    params.require(:user).permit(:username, :name, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_categories_helper.rb
module BookCategoriesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_books_helper.rb
module FavoriteBooksHelper
end

app/helpers/favorite_rhymes_helper.rb
module FavoriteRhymesHelper
end

app/helpers/rhyme_categories_helper.rb
module RhymeCategoriesHelper
end

app/helpers/rhymes_helper.rb
module RhymesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="index-content">
    <div class="title">
        <h1> Books 📚</h1>
    </div>

    <% @categories.each do |category| %>
        <h2><%= category.name %>:</h2>
    
        <% category.books.each do |book|  %>
            <%= link_to book_path(book) do %>
                <%= image_tag "#{asset_path book.img_url}", class: "img-link" %>
            <% end %>
        <% end %>
    

    <% end %>
</div>









 

app/views/books/show.html.erb
<div class="title show">
<h1> 
<%= @book.title %>
</h1>
<h3> Written by: <%= @book.author %></h3>
</div>

<div class="video">
<iframe width="840" height="465" src= <%="#{@book.video_url}"%>  frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<%# button_to "All Books 📚", books_path, method: :get %>

<div class = "show-buttons">
<% if FavoriteBook.find_by(user_id: @user.id, book_id: @book.id) %>
  <%= button_to "Unfavorite ❌", {controller: "books", action: "favorite"}, {class: "fav-button"} %>
<% else %>
  <%= button_to "Favorite ⭐️", {controller: "books", action: "favorite"}, {class:"fav-button"} %>
<% end %>
</div>

app/views/rhymes/index.html.erb
<div class="index-content">

    <div class="title">
        <h1> Nursery Rhymes 🥁 </h1>
    </div>

    <% @categories.each do |category| %>
        <h2><%= category.name %>:</h2>

        <% category.rhymes.each do |rhyme|  %>
            <%= link_to rhyme_path(rhyme) do %>
                <%= image_tag "#{asset_path rhyme.img_url}", class: "img-link" %>
            <% end %>
        <% end %>

    <% end %>
</div>

   

   
   

app/views/rhymes/show.html.erb
<div class="title show">
<h1> 
  <%= @rhyme.title %>
</h1>
</div>

<div class="video">
<iframe width="840" height="465" src= <%="#{@rhyme.video_url}"%>  frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<%# button_to "All Rhymes 📚", rhymes_path, method: :get %>

<div class = "show-buttons">
<% if FavoriteRhyme.find_by(user_id: @user.id, rhyme_id: @rhyme.id) %>
  <%= button_to "Unfavorite ❌", {controller: "rhymes", action: "favorite"}, {class: "fav-button"} %>
<% else %>
  <%= button_to "Favorite ⭐️", {controller: "rhymes", action: "favorite"}, {class: "fav-button"} %>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :username %><br>
    <%= f.text_field :username, class:'form-element'%><br/>
  
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-element'%><br/>
  
    <%= f.label :age %><br>
    <%= f.number_field :age, class:'form-element'%><br/>
  
    <%= f.submit class:'submit-button create-edit-button' %>
  <% end %>

app/views/users/_nav.html.erb
<div id="navbar">
  <div class="nav-element left-element">
    <%= link_to "Home 🏠", user_path(session[:user_id])%>
  </div>

  <div class="nav-element middle-elements">
    <%= link_to "Books 📚", books_path %>
  </div>
  <div class="nav-element middle-elements">
    <%= link_to "Rhymes 🥁", rhymes_path %>
  </div>

  <div class="nav-element right-element">
    <%= link_to "👤 Logout", logout_path, method: :delete %>
  </div>
</div>

app/views/users/edit.html.erb
<div class = "title"><h1>Edit your Account</h1></div>
<div class="edit-user-form">
<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <h4>OOPS! <%= msg %></h4>
  <% end %>
<% end %>

<%= render 'form' %>
</div>

app/views/users/home.html.erb
<img id="logo" src = "https://lh3.googleusercontent.com/pw/ACtC-3fmsbCNUTvwUXPsTkcmq5jlPfAFfsmby46UWWiDuCecmtz9t5b0HjCJSzs8K5h9Ty4Py1a57vZ6IFX_WpjshaqnedFAPTS33wpFgyblaW_uoDt5NwqqVn58ZkJyzjxahJG21dIkEm_DEYDiayjyzGM-=w1684-h540-no">


<div class="home-buttons-container">
    <%= button_to "Login", login_path, method: :get, class: "home-button" %>
    <%= button_to "Create Account", new_user_path, method: :get, class: "home-button" %>
</div>


<div class="music">
<audio controls autoplay loop>
  <source src="https://retired.sounddogs.com/previews/2515/mp3/687222_SOUNDDOGS__mu.mp3" type="audio/ogg" >
  <embed src="https://retired.sounddogs.com/previews/2515/mp3/687222_SOUNDDOGS__mu.mp3" autostart="true" loop="true" hidden="true"> 
</audio>
</div>

app/views/users/login.html.erb
<div class="title"><h1>Login:</h1></div>


<div class="login-form">

    <% if flash[:failed] %>
        <%= flash[:failed] %><br><br>
    <% end %>

    <%= form_tag find_user_path, method: "get" do %>

        <label> Username:</label>
 <div class= "login-button-form">
        <%= text_field_tag :username%>

        <%= submit_tag "Login", class: "submit-button" %>
</div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class = "title"><h1>Create A New User Account</h1></div>
<div class="new-user-form">
<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <h4>OOPS! <%= msg %></h4>
  <% end %>
<% end %>

<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class= "index-content">
<div class= "name"><h1>  Hi <%= @user.name %>! 👋</h1></div>


    <%= flash[:errors] if flash[:errors]%>


<div class = "age"><h2> You are <%= @user.age %> years old!</h2></div>



<h2> Your Favorite Books: </h2>

<% if @user.books.empty? %>
    <p> You have no favorite books yet. </p>
<% else %>   
    <% @user.books.each do |book| %> 
        <%= link_to book_path(book) do %>
            <%= image_tag "#{asset_path book.img_url}", class: "img-link" %>
        <% end %>
    <% end %> 
<% end %>

<%# button_to "See All Books 📚", books_path,  method: :get %>



<h2> Your Favorite Nursery Rhymes: </h2>

<% if @user.rhymes.empty? %>
<p> You have no favorite nursery rhymes yet. </p>
<% else %>
    <% @user.rhymes.each do |rhyme| %> 
            <%= link_to rhyme_path(rhyme) do %>
                <%= image_tag "#{asset_path rhyme.img_url}", class: "img-link" %>
            <% end %>
    <% end %> 
    
<% end %><br>

<%# button_to "See All Nursery Rhymes 🥁", rhymes_path,  method: :get %>

<div class="user-buttons">
<%= button_to "Edit Your Account", edit_user_path(@user),  method: :get, class: "user-button edit-account" %>
<%= button_to "Delete Your Account", user_path(@user),  method: :delete, class: "user-button delete-account" %>

</div>

</div>